update mission 2 & 6 Chinese translation
FlowFans/crypto-dappy-learning-hub pull request #10
Opened 2021-09-27 08:01 UTC by firevenus

2021-09-28 06:50 UTC, btspoony commented
mdx 内嵌视频的方式不太对
看下其他mission-{n}.cn.mdx吧
还有b站上的视频链接也要补一下哈

2021-09-28 15:27 UTC, firevenus commented
> mdx 内嵌视频的方式不太对 看下其他mission-{n}.cn.mdx吧 还有b站上的视频链接也要补一下哈

Corrected. Thx.

2021-09-29 01:58 UTC, btspoony requested changes

2021-09-29 01:58 UTC, btspoony commented on src/missions/mission-6.cn.mdx
> +<iframe src="https://www.youtube.com/embed/ev7LwnH0gl0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="" title="Embedded youtube" wi
这里格式还是错了。。。，iframe都要改掉。。

2021-09-29 01:58 UTC, btspoony commented on src/missions/mission-6.cn.mdx
> +<BilibiliEmbed embedId="BV1q64y1h7Hd"/>
Bilibili的视频做个简单介绍吧，参考下其他cn.mdx里的介绍

2021-09-29 01:58 UTC, btspoony commented on src/missions/mission-2.cn.mdx
> +<BilibiliEmbed embedId="BV11g411F7FV"/>
Bilibili的视频做个简单介绍吧，参考下其他cn.mdx里的介绍

2021-10-20 13:36 UTC, btspoony approved these changes
先这样吧

2021-10-20 13:36 UTC, merged